
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'sexpr_listID LPAREN NUMBER RPARENsexpr_list : sexpr\n                  | sexpr_list sexprsexpr : LPAREN ID param_list RPARENparam_list : param\n                  | param_list paramparam : LPAREN ID NUMBER RPAREN'
    
_lr_action_items = {'LPAREN':([0,1,2,4,5,7,8,10,11,13,],[3,3,-1,-2,6,6,-4,-3,-5,-6,]),'$end':([1,2,4,10,],[0,-1,-2,-3,]),'ID':([3,6,],[5,9,]),'RPAREN':([7,8,11,12,13,],[10,-4,-5,13,-6,]),'NUMBER':([9,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sexpr_list':([0,],[1,]),'sexpr':([0,1,],[2,4,]),'param_list':([5,],[7,]),'param':([5,7,],[8,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sexpr_list","S'",1,None,None,None),
  ('sexpr_list -> sexpr','sexpr_list',1,'p_sexpr_list','interpret.py',35),
  ('sexpr_list -> sexpr_list sexpr','sexpr_list',2,'p_sexpr_list','interpret.py',36),
  ('sexpr -> LPAREN ID param_list RPAREN','sexpr',4,'p_sexpr','interpret.py',43),
  ('param_list -> param','param_list',1,'p_param_list','interpret.py',47),
  ('param_list -> param_list param','param_list',2,'p_param_list','interpret.py',48),
  ('param -> LPAREN ID NUMBER RPAREN','param',4,'p_param','interpret.py',55),
]
